import Head from 'next/head';

import Navbar from '../components/Navbar';
import Home from '../components/Home';
import About from '../components/About';
import Skill from '../components/Skill';
import Project from '../components/Project';
import Contact from '../components/Contact';
import Game from '../components/Game';
import ThreeCanvas from '@/components/ThreeCanvas';

export default function Index() {
  return (
    <>
      <Head>
        <title>Yuugou Ohno</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Home />
      <About />
      <Skill />
      <Project />
      <Contact />
      <Game />
      <ThreeCanvas />
    </>
  )
}
