import Head from 'next/head';

import BackgroundImage from "@/components/home/BackgroundImage";
import BackCanvas from '@/components/three/BackCanvas';
import FrontCanvas from '@/components/three/FrontCanvas';

import Navbar from '@/components/elements/Navbar';
import Home from '@/components/home/Home';
import About from '@/components/aboutSection/About';
import Project from '@/components/projectSection/Project';
import Contact from '@/components/contactSection/Contact';
import Bye from '@/components/Bye';
import Presentation from '@/components/presentationSection/Presentation'
import Game from '@/components/gameSection/Game'


export default function Index() {
  return (
    <div>
      <Head>
        <title>Yuugou Ohno</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <BackgroundImage />
      <BackCanvas />
      {/* <FrontCanvas /> */}
      <Home />
      <About />
      <Project />
      <Contact />
      <Bye />
      <Presentation />
      <Game />
    </div>
  )
}
